language: php
dist: trusty
sudo: false

matrix:
  include:
      env:
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.0
    - php: 7.3
      env:
        - LARAVEL_VERSION=5.7.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.0

install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - composer require "symfony/lts:${SYMFONY_VERSION}" --no-update -n
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.2" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi