INSERT INTO `d_scan_datas` (`ship_name`, `ship_type`, `ship_class`) VALUES
	('Abaddon', 'Battleship', 'DPS'),
	('Absolution', 'Cmd. Ship', 'DPS'),
	('Adrestia', 'Cruiser', 'DPS'),
	('Aeon', 'Supercarrier', 'Supercap'),
	('Algos', 'Destroyer', 'Support'),
	('Anathema', 'Covert Ops', 'Prober'),
	('Anshar', 'Jump Freighter', 'Jump Freighter'),
	('Apocalypse', 'Battleship', 'DPS'),
	('Apocalypse Navy Issue', 'Battleship', 'DPS'),
	('Apostle', 'Force Auxillary', 'Cap Logi'),
	('Apotheosis', 'Shuttle', 'Trash'),
	('Arazu', 'Force Recon', 'Heavy Tackle'),
	('Arbitrator', 'Cruiser', 'Cruiser'),
	('Archon', 'Carrier', 'Capital'),
	('Ares', 'Interceptor', 'Tackle'),
	('Ark', 'Jump Freighter', 'Jump Freighter'),
	('Armageddon', 'Battleship', 'DPS'),
	('Armageddon Navy Issue', 'Battleship', 'DPS'),
	('Ashimmu', 'Cruiser', 'Support'),
	('Astarte', 'Cmd. Ship', 'Support'),
	('Astarte', 'Frigate', 'Prober'),
	('Atron', 'Frigate', 'Tackle'),
	('Augoror', 'Cruiser', 'T1 Logi'),
	('Augoror Navy Issue', 'Cruiser', 'Cruiser'),
	('Avatar', 'Titan', 'Supercap'),
	('Badger', 'Industrial', 'Hauler'),
	('Bantam', 'Frigate', 'Tackle'),
	('Barghest', 'Cruiser', 'DPS'),
	('Basilisk', 'Logistics', 'Logistics'),
	('Bellicose', 'Cruiser', 'T1 Logi'),
	('Bestower', 'Industrial', 'Hauler'),
	('Bhaalgorn', 'Battleship', 'DPS'),
	('Bifrost', 'Command Destroyer', 'Jumper'),
	('Blackbird', 'Cruiser', 'EWAR'),
	('Bowhead', 'Freighter', 'Freighter'),
	('Breacher', 'Frigate', 'Tackle'),
	('Broadsword', 'Hictor', 'Bubbler'),
	('Brutix', 'Battlecruiser', 'DPS'),
	('Brutix Navy Issue', 'Battlecruiser', 'DPS'),
	('Burst', 'Frigate', 'Tackle'),
	('Bustard', 'Transport', 'T2 Non Cloaky Hauler'),
	('Buzzard', 'Covert Ops', 'Prober'),
	('Caiman', 'Dreadnought', 'Capital'),
	('Caldari Navy Hookbill', 'Frigate', 'Tackle'),
	('Caracal', 'Cruiser', 'DPS'),
	('Caracal Navy Issue', 'Cruiser', 'DPS'),
	('Catalyst', 'Destroyer', 'Support'),
	('Celestis', 'Cruiser', 'Cruiser'),
	('Cerberus', 'H.A. Cruiser', 'DPS'),
	('Charon', 'Freighter', 'Freighter'),
	('Cheetah', 'Covert Ops', 'Prober'),
	('Chemosh', 'Dreadnought', 'Capital'),
	('Chimera', 'Carrier', 'Capital'),
	('Claw', 'Interceptor', 'Tackle'),
	('Claymore', 'Cmd. Ship', 'Booster'),
	('Coercer', 'Destroyer', 'Tackle'),
	('Condor', 'Frigate', 'Tackle'),
	('Confessor', 'T3 Destroyer', 'DPS'),
	('Corax', 'Destroyer', 'Support'),
	('Cormorant', 'Destroyer', 'Support'),
	('Covetor', 'Mining Barge', 'Miner'),
	('Crane', 'Blockade Run.', 'Cloaky Hauler'),
	('Crow', 'Interceptor', 'Tackle'),
	('Crucifier', 'Frigate', 'Tackle'),
	('Crucifier Navy Issue', 'Frigate', 'Tackle'),
	('Cruor', 'Frigate', 'Tackle'),
	('Crusader', 'Interceptor', 'Tackle'),
	('Curse', 'Combat Recon', 'Neuts'),
	('Cyclone', 'Battlecruiser', 'DPS'),
	('Cynabal', 'Cruiser', 'DPS'),
	('Dagon', 'Force Auxillary', 'Cap Logi'),
	('Damavik', 'Triglavian Frigate', 'DPS'),
	('Damnation', 'Cmd. Ship', 'Booster'),
	('Daredevil', 'Frigate', 'Tackle'),
	('Deacon', 'Logi Frig', 'Logistics'),
	('Deimos', 'H.A. Cruiser', 'DPS'),
	('Devoter', 'Hictor', 'Bubbler'),
	('Dominix', 'Battleship', 'DPS'),
	('Dominix Navy Issue', 'Battleship', 'DPS'),
	('Dragoon', 'Destroyer', 'Support'),
	('Drake', 'Battlecruiser', 'DPS'),
	('Drake Navy Issue', 'Battlecruiser', 'DPS'),
	('Dramiel', 'Frigate', 'Tackle'),
	('Drakavac', 'Triglavian BC', 'DPS'),
	('Eagle', 'H.A. Cruiser', 'DPS'),
	('Echelon', 'Frigate', 'Trash'),
	('Endurance', 'Cov. Mining Frig', 'Mining'),
	('Enforcer', 'Force Recon', 'EWAR'),
	('Enyo', 'Assault Frig.', 'Tackle'),
	('Eos', 'Cmd. Ship', 'Booster'),
	('Epithal', 'Industrial', 'Hauler'),
	('Erebus', 'Titan', 'Supercap'),
	('Eris', 'Interdictor', 'Bubbler'),
	('Executioner', 'Frigate', 'Tackle'),
	('Exequror Navy Issue', 'Cruiser', 'T1 Logi'),
	('Exequror', 'Cruiser', 'T1 Logi'),
	('Falcon', 'Force Recon', 'EWAR'),
	('Federation Navy Comet', 'Frigate', 'Tackle'),
	('Fenrir', 'Freighter', 'Freighter'),
	('Ferox', 'Battlecruiser', 'DPS'),
	('Flycatcher', 'Interdictor', 'Bubbler'),
	('Freki', 'Frigate', 'Tackle'),
	('Garmur', 'Cruiser', 'DPS'),
	('Gila', 'Cruiser', 'DPS'),
	('Gnosis', 'Cruiser', 'DPS'),
	('Golem', 'Marauder', 'DPS'),
	('Griffin', 'Frigate', 'EWAR'),
	('Griffin Navy Issue', 'Frigate', 'EWAR'),
	('Guardian', 'Logistics', 'Logistics'),
	('Harbinger', 'Battlecruiser', 'DPS'),
	('Harbinger Navy Issue', 'Battlecruiser', 'DPS'),
	('Harpy', 'Assault Frig.', 'Tackle'),
	('Hawk', 'Assault Frig.', 'Tackle'),
	('Hecate', 'T3 Destroyer', 'DPS'),
	('Hel', 'Supercarrier', 'Supercap'),
	('Helios', 'Covert Ops', 'Prober'),
	('Heretic', 'Interdictor', 'Bubbler'),
	('Heron', 'Frigate', 'Tackle'),
	('Hoarder', 'Industrial', 'Hauler'),
	('Hound', 'S. Bomber', 'Bomber'),
	('Huginn', 'Combat Recon', 'Heavy Tackle'),
	('Hulk', 'Exhumer', 'Miner'),
	('Hurricane', 'Battlecruiser', 'DPS'),
	('Hurricane Fleet Issue', 'Battlecruiser', 'DPS'),
	('Hydra', 'Cov. Ops. Triglavian Frig', 'DPS'),
	('Hyena', 'EWAR Frig.', 'Tackle'),
	('Hyperion', 'Battleship', 'DPS'),
	('Ibis', 'Corvette', 'Trash'),
	('Imicus', 'Frigate', 'Tackle'),
	('Impairor', 'Corvette', 'Trash'),
	('Imperial Navy Slicer', 'Frigate', 'Tackle'),
	('Impel', 'Transport', 'T2 Non Cloaky Hauler'),
	('Incursus', 'Frigate', 'Tackle'),
	('Inquisitor', 'Frigate', 'Tackle'),
	('Ishkur', 'Assault Frig.', 'Tackle'),
	('Ishtar', 'H.A. Cruiser', 'DPS'),
	('Iteron Mark V', 'Industrial', 'Hauler'),
	('Jackdaw', 'T3 Destroyer', 'DPS'),
	('Jaguar', 'Assault Frig.', 'Tackle'),
	('Keres', 'EWAR Frig.', 'Tackle'),
	('Kestrel', 'Frigate', 'Tackle'),
	('Kikimore', 'Triglavian Destroyer', 'DPS'),
	('Kirin', 'Logi Frig', 'Logistics'),
	('Kitsune', 'EWAR Frig.', 'EWAR'),
	('Komodo', 'Titan', 'Supercap'),
	('Kronos', 'Marauder', 'DPS'),
	('Kryos', 'Industrial', 'Hauler'),
	('Lachesis', 'Combat Recon', 'Heavy Tackle'),
	('Legion', 'Strat. Cruiser', 'DPS'),
	('Leshak', 'Triglavian Battleship', 'DPS'),
	('Leviathan', 'Titan', 'Supercap'),
	('Lif', 'Force Auxillary', 'Cap Logi'),
	('Loggerhead', 'Force Auxillary', 'Cap Logi'),
	('Loki', 'Strat. Cruiser', 'Heavy Tackle'),
	('Machariel', 'Battleship', 'DPS'),
	('Mackinaw', 'Exhumer', 'Miner'),
	('Maelstrom', 'Battleship', 'DPS'),
	('Magnate', 'Frigate', 'Tackle'),
	('Magus', 'Command Destroyer', 'Jumper'),
	('Malediction', 'Interceptor', 'Tackle'),
	('Maller', 'Cruiser', 'Cruiser'),
	('Mammoth', 'Industrial', 'Hauler'),
	('Manticore', 'S. Bomber', 'Bomber'),
	('Marshal', 'Battleship', 'DPS'),
	('Mastodon', 'Transport', 'T2 Non Cloaky Hauler'),
	('Maulus', 'Frigate', 'Tackle'),
	('Maulus Navy Issue', 'Frigate', 'Tackle'),
	('Megathron', 'Battleship', 'DPS'),
	('Megathron Navy Issue', 'Battleship', 'DPS'),
	('Merlin', 'Frigate', 'Tackle'),
	('Miasmos', 'Industrial', 'Hauler'),
	('Mimir', 'Cruiser', 'DPS'),
	('Minokawa', 'Force Auxillary', 'Cap Logi'),
	('Moa', 'Cruiser', 'Cruiser'),
	('Molok', 'Titan', 'Supercap'),
	('Moros', 'Dreadnought', 'Capital'),
	('Muninn', 'H.A. Cruiser', 'DPS'),
	('Myrmidon', 'Battlecruiser', 'DPS'),
	('Naga', 'Battlecruiser', 'DPS'),
	('Naglfar', 'Dreadnought', 'Capital'),
	('Navitas', 'Frigate', 'Tackle'),
	('Nemesis', 'S. Bomber', 'Bomber'),
	('Nereus', 'Industrial', 'Hauler'),
	('Nestor', 'Battleship', 'DPS'),
	('Nidhoggur', 'Carrier', 'Capital'),
	('Nighthawk', 'Cmd. Ship', 'DPS'),
	('Nightmare', 'Battleship', 'DPS'),
	('Ninazu', 'Force Auxillary', 'Cap Logi'),
	('Noctis', 'Salvaging', 'Trash'),
	('Nomad', 'Jump Freighter', 'Jump Freighter'),
	('Nyx', 'Supercarrier', 'Supercap'),
	('Obelisk', 'Freighter', 'Freighter'),
	('Occator', 'Transport', 'T2 Non Cloaky Hauler'),
	('Omen', 'Cruiser', 'DPS'),
	('Omen Navy Issue', 'Cruiser', 'DPS'),
	('Oneiros', 'Logistics', 'Logistics'),
	('Onyx', 'Hictor', 'Bubbler'),
	('Oracle', 'Battlecruiser', 'DPS'),
	('Orca', 'Ind. Cmd.', 'Ind. Cmd.'),
	('Orthrus', 'Cruiser', 'DPS'),
	('Osprey', 'Cruiser', 'T1 Logi'),
	('Osprey Navy Issue', 'Cruiser', 'DPS'),
	('Paladin', 'Marauder', 'DPS'),
	('Panther', 'Black Ops', 'Black Ops'),
	('Phantasm', 'Cruiser', 'Support'),
	('Phobos', 'Hictor', 'Bubbler'),
	('Phoenix', 'Dreadnought', 'Capital'),
	('Pilgrim', 'Force Recon', 'Support'),
	('Pontifax', 'Command Destroyer', 'Jumper'),
	('Porpoise', 'Ind. Cmd.', 'Ind. Cmd.'),
	('Praxis', 'Battleship', 'DPS'),
	('Primae', 'Industrial', 'Trash'),
	('Probe', 'Frigate', 'Tackle'),
	('Procurer', 'Mining Barge', 'Miner'),
	('Prophecy', 'Battlecruiser', 'DPS'),
	('Prorator', 'Blockade Run.', 'Cloaky Hauler'),
	('Prospect', 'Cov. Op. Miner', 'Miner'),
	('Proteus', 'Strat. Cruiser', 'Heavy Tackle'),
	('Providence', 'Freighter', 'Freighter'),
	('Prowler', 'Blockade Run.', 'Cloaky Hauler'),
	('Punisher', 'Frigate', 'Tackle'),
	('Purifier', 'S. Bomber', 'Bomber'),
	('Ragnarok', 'Titan', 'Supercap'),
	('Rapier', 'Force Recon', 'Heavy Tackle'),
	('Raptor', 'Interceptor', 'Tackle'),
	('Rattlesnake', 'Battleship', 'DPS'),
	('Raven', 'Battleship', 'DPS'),
	('Raven Navy Issue', 'Battleship', 'DPS'),
	('Reaper', 'Frigate', 'Trash'),
	('Redeemer', 'Black Ops', 'Black Ops'),
	('Republic Fleet Firetail', 'Frigate', 'Tackle'),
	('Retribution', 'Assault Frig.', 'Tackle'),
	('Retriever', 'Mining Barge', 'Miner'),
	('Revelation', 'Dreadnought', 'Capital'),
	('Revenant', 'Supercarrier', 'Supercap'),
	('Rhea', 'Jump Freighter', 'Jump Freighter'),
	('Rifter', 'Frigate', 'Tackle'),
	('Rodiva', 'Triglavian Logi', 'Logistics'),
	('Rokh', 'Battleship', 'DPS'),
	('Rook', 'Combat Recon', 'EWAR'),
	('Rorqual', 'Cap. Ind.', 'Capital'),
	('Rupture', 'Cruiser', 'Cruiser'),
	('Sabre', 'Interdictor', 'Bubbler'),
	('Sacrilege', 'H.A. Cruiser', 'DPS'),
	('Scalpel', 'Logi Frig', 'Logistics'),
	('Scimitar', 'Logistics', 'Logistics'),
	('Scorpion', 'Battleship', 'DPS'),
	('Scythe', 'Cruiser', 'T1 Logi'),
	('Scythe Fleet Issue', 'Cruiser', 'Cruiser'),
	('Sentinel', 'EWAR Frig.', 'Neuts'),
	('Sigil', 'Industrial', 'Hauler'),
	('Sin', 'Black Ops', 'Black Ops'),
	('Skiff', 'Exhumer', 'Miner'),
	('Slasher', 'Frigate', 'Tackle'),
	('Sleipnir', 'Cmd. Ship', 'DPS'),
	('Stabber', 'Cruiser', 'DPS'),
	('Stabber Fleet Issue', 'Cruiser', 'DPS'),
	('Stiletto', 'Interceptor', 'Tackle'),
	('Stork', 'Command Destroyer', 'Jumper'),
	('Stratios', 'Cov. op. Cruiser', 'DPS'),
	('Succubus', 'Frigate', 'Tackle'),
	('Sunesis', 'Destroyer', 'DPS'),
	('Svipul', 'T3 Destroyer', 'DPS'),
	('Talos', 'Battlecruiser', 'DPS'),
	('Talwar', 'Destroyer', 'Support'),
	('Taranis', 'Interceptor', 'Tackle'),
	('Tayra', 'Industrial', 'Hauler'),
	('Tempest', 'Battleship', 'DPS'),
	('Tempest Fleet Issue', 'Battleship', 'DPS'),
	('Tengu', 'Strat. Cruiser', 'DPS'),
	('Thalia', 'Logi Frig', 'Logistics'),
	('Thanatos', 'Carrier', 'Capital'),
	('Thorax', 'Cruiser', 'Cruiser'),
	('Thrasher', 'Destroyer', 'Support'),
	('Tiamar', 'Triglavian Cov. Op. Cruiser', 'DPS'),
	('Tormentor', 'Frigate', 'Tackle'),
	('Tornado', 'Battlecruiser', 'DPS'),
	('Tristan', 'Frigate', 'Tackle'),
	('Typhoon', 'Battleship', 'DPS'),
	('Utu', 'Frigate', 'DPS'),
	('Vagabond', 'H.A. Cruiser', 'DPS'),
	('Vanguard', 'Carrier', 'Capital'),
	('Vanquisher', 'Titan', 'Supercap'),
	('Vargur', 'Marauder', 'DPS'),
	('Vedmak', 'Triglavian Cruiser', 'DPS'),
	('Vehement', 'Dreadnought', 'Capital'),
	('Velator', 'Frigate', 'Trash'),
	('Vendetta', 'Supercarrier', 'Supercap'),
	('Venerable', 'Force Auxillary', 'Cap Logi'),
	('Vengeance', 'Assault Frig.', 'Tackle'),
	('Venture', 'Frigate', 'Trash'),
	('Vexor', 'Cruiser', 'DPS'),
	('Vexor Navy Issue', 'Cruiser', 'DPS'),
	('Viator', 'Blockade Run.', 'Cloaky Hauler'),
	('Vigil', 'Frigate', 'Tackle'),
	('Vigilant', 'Cruiser', 'DPS'),
	('Vindicator', 'Battleship', 'DPS'),
	('Vulture', 'Cmd. Ship', 'Booster'),
	('Widow', 'Black Ops', 'Black Ops'),
	('Wolf', 'Assault Frig.', 'Tackle'),
	('Worm', 'Frigate', 'Tackle'),
	('Wreathe', 'Industrial', 'Hauler'),
	('Wyvern', 'Supercarrier', 'Supercap'),
	('Zealot', 'H.A. Cruiser', 'DPS'),
	('Zephyr', 'Shuttle', 'Trash'),
	('Abaddon', 'Battleship', 'DPS'),
	('Absolution', 'Cmd. Ship', 'DPS'),
	('Adrestia', 'Cruiser', 'DPS'),
	('Aeon', 'Supercarrier', 'Supercap'),
	('Algos', 'Destroyer', 'Support'),
	('Anathema', 'Covert Ops', 'Prober'),
	('Anshar', 'Jump Freighter', 'Jump Freighter'),
	('Apocalypse', 'Battleship', 'DPS'),
	('Apocalypse Navy Issue', 'Battleship', 'DPS'),
	('Apostle', 'Force Auxillary', 'Cap Logi'),
	('Apotheosis', 'Shuttle', 'Trash'),
	('Arazu', 'Force Recon', 'Heavy Tackle'),
	('Arbitrator', 'Cruiser', 'Cruiser'),
	('Archon', 'Carrier', 'Capital'),
	('Ares', 'Interceptor', 'Tackle'),
	('Ark', 'Jump Freighter', 'Jump Freighter'),
	('Armageddon', 'Battleship', 'DPS'),
	('Armageddon Navy Issue', 'Battleship', 'DPS'),
	('Ashimmu', 'Cruiser', 'Support'),
	('Astarte', 'Cmd. Ship', 'Support'),
	('Astarte', 'Frigate', 'Prober'),
	('Atron', 'Frigate', 'Tackle'),
	('Augoror', 'Cruiser', 'T1 Logi'),
	('Augoror Navy Issue', 'Cruiser', 'Cruiser'),
	('Avatar', 'Titan', 'Supercap'),
	('Badger', 'Industrial', 'Hauler'),
	('Bantam', 'Frigate', 'Tackle'),
	('Barghest', 'Cruiser', 'DPS'),
	('Basilisk', 'Logistics', 'Logistics'),
	('Bellicose', 'Cruiser', 'T1 Logi'),
	('Bestower', 'Industrial', 'Hauler'),
	('Bhaalgorn', 'Battleship', 'DPS'),
	('Bifrost', 'Command Destroyer', 'Jumper'),
	('Blackbird', 'Cruiser', 'EWAR'),
	('Bowhead', 'Freighter', 'Freighter'),
	('Breacher', 'Frigate', 'Tackle'),
	('Broadsword', 'Hictor', 'Bubbler'),
	('Brutix', 'Battlecruiser', 'DPS'),
	('Brutix Navy Issue', 'Battlecruiser', 'DPS'),
	('Burst', 'Frigate', 'Tackle'),
	('Bustard', 'Transport', 'T2 Non Cloaky Hauler'),
	('Buzzard', 'Covert Ops', 'Prober'),
	('Caiman', 'Dreadnought', 'Capital'),
	('Caldari Navy Hookbill', 'Frigate', 'Tackle'),
	('Caracal', 'Cruiser', 'DPS'),
	('Caracal Navy Issue', 'Cruiser', 'DPS'),
	('Catalyst', 'Destroyer', 'Support'),
	('Celestis', 'Cruiser', 'Cruiser'),
	('Cerberus', 'H.A. Cruiser', 'DPS'),
	('Charon', 'Freighter', 'Freighter'),
	('Cheetah', 'Covert Ops', 'Prober'),
	('Chemosh', 'Dreadnought', 'Capital'),
	('Chimera', 'Carrier', 'Capital'),
	('Claw', 'Interceptor', 'Tackle'),
	('Claymore', 'Cmd. Ship', 'Booster'),
	('Coercer', 'Destroyer', 'Tackle'),
	('Condor', 'Frigate', 'Tackle'),
	('Confessor', 'T3 Destroyer', 'DPS'),
	('Corax', 'Destroyer', 'Support'),
	('Cormorant', 'Destroyer', 'Support'),
	('Covetor', 'Mining Barge', 'Miner'),
	('Crane', 'Blockade Run.', 'Cloaky Hauler'),
	('Crow', 'Interceptor', 'Tackle'),
	('Crucifier', 'Frigate', 'Tackle'),
	('Crucifier Navy Issue', 'Frigate', 'Tackle'),
	('Cruor', 'Frigate', 'Tackle'),
	('Crusader', 'Interceptor', 'Tackle'),
	('Curse', 'Combat Recon', 'Neuts'),
	('Cyclone', 'Battlecruiser', 'DPS'),
	('Cynabal', 'Cruiser', 'DPS'),
	('Dagon', 'Force Auxillary', 'Cap Logi'),
	('Damavik', 'Triglavian Frigate', 'DPS'),
	('Damnation', 'Cmd. Ship', 'Booster'),
	('Daredevil', 'Frigate', 'Tackle'),
	('Deacon', 'Logi Frig', 'Logistics'),
	('Deimos', 'H.A. Cruiser', 'DPS'),
	('Devoter', 'Hictor', 'Bubbler'),
	('Dominix', 'Battleship', 'DPS'),
	('Dominix Navy Issue', 'Battleship', 'DPS'),
	('Dragoon', 'Destroyer', 'Support'),
	('Drake', 'Battlecruiser', 'DPS'),
	('Drake Navy Issue', 'Battlecruiser', 'DPS'),
	('Dramiel', 'Frigate', 'Tackle'),
	('Drakavac', 'Triglavian BC', 'DPS'),
	('Eagle', 'H.A. Cruiser', 'DPS'),
	('Echelon', 'Frigate', 'Trash'),
	('Endurance', 'Cov. Mining Frig', 'Mining'),
	('Enforcer', 'Force Recon', 'EWAR'),
	('Enyo', 'Assault Frig.', 'Tackle'),
	('Eos', 'Cmd. Ship', 'Booster'),
	('Epithal', 'Industrial', 'Hauler'),
	('Erebus', 'Titan', 'Supercap'),
	('Eris', 'Interdictor', 'Bubbler'),
	('Executioner', 'Frigate', 'Tackle'),
	('Exequror Navy Issue', 'Cruiser', 'T1 Logi'),
	('Exequror', 'Cruiser', 'T1 Logi'),
	('Falcon', 'Force Recon', 'EWAR'),
	('Federation Navy Comet', 'Frigate', 'Tackle'),
	('Fenrir', 'Freighter', 'Freighter'),
	('Ferox', 'Battlecruiser', 'DPS'),
	('Flycatcher', 'Interdictor', 'Bubbler'),
	('Freki', 'Frigate', 'Tackle'),
	('Garmur', 'Cruiser', 'DPS'),
	('Gila', 'Cruiser', 'DPS'),
	('Gnosis', 'Cruiser', 'DPS'),
	('Golem', 'Marauder', 'DPS'),
	('Griffin', 'Frigate', 'EWAR'),
	('Griffin Navy Issue', 'Frigate', 'EWAR'),
	('Guardian', 'Logistics', 'Logistics'),
	('Harbinger', 'Battlecruiser', 'DPS'),
	('Harbinger Navy Issue', 'Battlecruiser', 'DPS'),
	('Harpy', 'Assault Frig.', 'Tackle'),
	('Hawk', 'Assault Frig.', 'Tackle'),
	('Hecate', 'T3 Destroyer', 'DPS'),
	('Hel', 'Supercarrier', 'Supercap'),
	('Helios', 'Covert Ops', 'Prober'),
	('Heretic', 'Interdictor', 'Bubbler'),
	('Heron', 'Frigate', 'Tackle'),
	('Hoarder', 'Industrial', 'Hauler'),
	('Hound', 'S. Bomber', 'Bomber'),
	('Huginn', 'Combat Recon', 'Heavy Tackle'),
	('Hulk', 'Exhumer', 'Miner'),
	('Hurricane', 'Battlecruiser', 'DPS'),
	('Hurricane Fleet Issue', 'Battlecruiser', 'DPS'),
	('Hydra', 'Cov. Ops. Triglavian Frig', 'DPS'),
	('Hyena', 'EWAR Frig.', 'Tackle'),
	('Hyperion', 'Battleship', 'DPS'),
	('Ibis', 'Corvette', 'Trash'),
	('Imicus', 'Frigate', 'Tackle'),
	('Impairor', 'Corvette', 'Trash'),
	('Imperial Navy Slicer', 'Frigate', 'Tackle'),
	('Impel', 'Transport', 'T2 Non Cloaky Hauler'),
	('Incursus', 'Frigate', 'Tackle'),
	('Inquisitor', 'Frigate', 'Tackle'),
	('Ishkur', 'Assault Frig.', 'Tackle'),
	('Ishtar', 'H.A. Cruiser', 'DPS'),
	('Iteron Mark V', 'Industrial', 'Hauler'),
	('Jackdaw', 'T3 Destroyer', 'DPS'),
	('Jaguar', 'Assault Frig.', 'Tackle'),
	('Keres', 'EWAR Frig.', 'Tackle'),
	('Kestrel', 'Frigate', 'Tackle'),
	('Kikimore', 'Triglavian Destroyer', 'DPS'),
	('Kirin', 'Logi Frig', 'Logistics'),
	('Kitsune', 'EWAR Frig.', 'EWAR'),
	('Komodo', 'Titan', 'Supercap'),
	('Kronos', 'Marauder', 'DPS'),
	('Kryos', 'Industrial', 'Hauler'),
	('Lachesis', 'Combat Recon', 'Heavy Tackle'),
	('Legion', 'Strat. Cruiser', 'DPS'),
	('Leshak', 'Triglavian Battleship', 'DPS'),
	('Leviathan', 'Titan', 'Supercap'),
	('Lif', 'Force Auxillary', 'Cap Logi'),
	('Loggerhead', 'Force Auxillary', 'Cap Logi'),
	('Loki', 'Strat. Cruiser', 'Heavy Tackle'),
	('Machariel', 'Battleship', 'DPS'),
	('Mackinaw', 'Exhumer', 'Miner'),
	('Maelstrom', 'Battleship', 'DPS'),
	('Magnate', 'Frigate', 'Tackle'),
	('Magus', 'Command Destroyer', 'Jumper'),
	('Malediction', 'Interceptor', 'Tackle'),
	('Maller', 'Cruiser', 'Cruiser'),
	('Mammoth', 'Industrial', 'Hauler'),
	('Manticore', 'S. Bomber', 'Bomber'),
	('Marshal', 'Battleship', 'DPS'),
	('Mastodon', 'Transport', 'T2 Non Cloaky Hauler'),
	('Maulus', 'Frigate', 'Tackle'),
	('Maulus Navy Issue', 'Frigate', 'Tackle'),
	('Megathron', 'Battleship', 'DPS'),
	('Megathron Navy Issue', 'Battleship', 'DPS'),
	('Merlin', 'Frigate', 'Tackle'),
	('Miasmos', 'Industrial', 'Hauler'),
	('Mimir', 'Cruiser', 'DPS'),
	('Minokawa', 'Force Auxillary', 'Cap Logi'),
	('Moa', 'Cruiser', 'Cruiser'),
	('Molok', 'Titan', 'Supercap'),
	('Moros', 'Dreadnought', 'Capital'),
	('Muninn', 'H.A. Cruiser', 'DPS'),
	('Myrmidon', 'Battlecruiser', 'DPS'),
	('Naga', 'Battlecruiser', 'DPS'),
	('Naglfar', 'Dreadnought', 'Capital'),
	('Navitas', 'Frigate', 'Tackle'),
	('Nemesis', 'S. Bomber', 'Bomber'),
	('Nereus', 'Industrial', 'Hauler'),
	('Nestor', 'Battleship', 'DPS'),
	('Nidhoggur', 'Carrier', 'Capital'),
	('Nighthawk', 'Cmd. Ship', 'DPS'),
	('Nightmare', 'Battleship', 'DPS'),
	('Ninazu', 'Force Auxillary', 'Cap Logi'),
	('Noctis', 'Salvaging', 'Trash'),
	('Nomad', 'Jump Freighter', 'Jump Freighter'),
	('Nyx', 'Supercarrier', 'Supercap'),
	('Obelisk', 'Freighter', 'Freighter'),
	('Occator', 'Transport', 'T2 Non Cloaky Hauler'),
	('Omen', 'Cruiser', 'DPS'),
	('Omen Navy Issue', 'Cruiser', 'DPS'),
	('Oneiros', 'Logistics', 'Logistics'),
	('Onyx', 'Hictor', 'Bubbler'),
	('Oracle', 'Battlecruiser', 'DPS'),
	('Orca', 'Ind. Cmd.', 'Ind. Cmd.'),
	('Orthrus', 'Cruiser', 'DPS'),
	('Osprey', 'Cruiser', 'T1 Logi'),
	('Osprey Navy Issue', 'Cruiser', 'DPS'),
	('Paladin', 'Marauder', 'DPS'),
	('Panther', 'Black Ops', 'Black Ops'),
	('Phantasm', 'Cruiser', 'Support'),
	('Phobos', 'Hictor', 'Bubbler'),
	('Phoenix', 'Dreadnought', 'Capital'),
	('Pilgrim', 'Force Recon', 'Support'),
	('Pontifax', 'Command Destroyer', 'Jumper'),
	('Porpoise', 'Ind. Cmd.', 'Ind. Cmd.'),
	('Praxis', 'Battleship', 'DPS'),
	('Primae', 'Industrial', 'Trash'),
	('Probe', 'Frigate', 'Tackle'),
	('Procurer', 'Mining Barge', 'Miner'),
	('Prophecy', 'Battlecruiser', 'DPS'),
	('Prorator', 'Blockade Run.', 'Cloaky Hauler'),
	('Prospect', 'Cov. Op. Miner', 'Miner'),
	('Proteus', 'Strat. Cruiser', 'Heavy Tackle'),
	('Providence', 'Freighter', 'Freighter'),
	('Prowler', 'Blockade Run.', 'Cloaky Hauler'),
	('Punisher', 'Frigate', 'Tackle'),
	('Purifier', 'S. Bomber', 'Bomber'),
	('Ragnarok', 'Titan', 'Supercap'),
	('Rapier', 'Force Recon', 'Heavy Tackle'),
	('Raptor', 'Interceptor', 'Tackle'),
	('Rattlesnake', 'Battleship', 'DPS'),
	('Raven', 'Battleship', 'DPS'),
	('Raven Navy Issue', 'Battleship', 'DPS'),
	('Reaper', 'Frigate', 'Trash'),
	('Redeemer', 'Black Ops', 'Black Ops'),
	('Republic Fleet Firetail', 'Frigate', 'Tackle'),
	('Retribution', 'Assault Frig.', 'Tackle'),
	('Retriever', 'Mining Barge', 'Miner'),
	('Revelation', 'Dreadnought', 'Capital'),
	('Revenant', 'Supercarrier', 'Supercap'),
	('Rhea', 'Jump Freighter', 'Jump Freighter'),
	('Rifter', 'Frigate', 'Tackle'),
	('Rodiva', 'Triglavian Logi', 'Logistics'),
	('Rokh', 'Battleship', 'DPS'),
	('Rook', 'Combat Recon', 'EWAR'),
	('Rorqual', 'Cap. Ind.', 'Capital'),
	('Rupture', 'Cruiser', 'Cruiser'),
	('Sabre', 'Interdictor', 'Bubbler'),
	('Sacrilege', 'H.A. Cruiser', 'DPS'),
	('Scalpel', 'Logi Frig', 'Logistics'),
	('Scimitar', 'Logistics', 'Logistics'),
	('Scorpion', 'Battleship', 'DPS'),
	('Scythe', 'Cruiser', 'T1 Logi'),
	('Scythe Fleet Issue', 'Cruiser', 'Cruiser'),
	('Sentinel', 'EWAR Frig.', 'Neuts'),
	('Sigil', 'Industrial', 'Hauler'),
	('Sin', 'Black Ops', 'Black Ops'),
	('Skiff', 'Exhumer', 'Miner'),
	('Slasher', 'Frigate', 'Tackle'),
	('Sleipnir', 'Cmd. Ship', 'DPS'),
	('Stabber', 'Cruiser', 'DPS'),
	('Stabber Fleet Issue', 'Cruiser', 'DPS'),
	('Stiletto', 'Interceptor', 'Tackle'),
	('Stork', 'Command Destroyer', 'Jumper'),
	('Stratios', 'Cov. op. Cruiser', 'DPS'),
	('Succubus', 'Frigate', 'Tackle'),
	('Sunesis', 'Destroyer', 'DPS'),
	('Svipul', 'T3 Destroyer', 'DPS'),
	('Talos', 'Battlecruiser', 'DPS'),
	('Talwar', 'Destroyer', 'Support'),
	('Taranis', 'Interceptor', 'Tackle'),
	('Tayra', 'Industrial', 'Hauler'),
	('Tempest', 'Battleship', 'DPS'),
	('Tempest Fleet Issue', 'Battleship', 'DPS'),
	('Tengu', 'Strat. Cruiser', 'DPS'),
	('Thalia', 'Logi Frig', 'Logistics'),
	('Thanatos', 'Carrier', 'Capital'),
	('Thorax', 'Cruiser', 'Cruiser'),
	('Thrasher', 'Destroyer', 'Support'),
	('Tiamar', 'Triglavian Cov. Op. Cruiser', 'DPS'),
	('Tormentor', 'Frigate', 'Tackle'),
	('Tornado', 'Battlecruiser', 'DPS'),
	('Tristan', 'Frigate', 'Tackle'),
	('Typhoon', 'Battleship', 'DPS'),
	('Utu', 'Frigate', 'DPS'),
	('Vagabond', 'H.A. Cruiser', 'DPS'),
	('Vanguard', 'Carrier', 'Capital'),
	('Vanquisher', 'Titan', 'Supercap'),
	('Vargur', 'Marauder', 'DPS'),
	('Vedmak', 'Triglavian Cruiser', 'DPS'),
	('Vehement', 'Dreadnought', 'Capital'),
	('Velator', 'Frigate', 'Trash'),
	('Vendetta', 'Supercarrier', 'Supercap'),
	('Venerable', 'Force Auxillary', 'Cap Logi'),
	('Vengeance', 'Assault Frig.', 'Tackle'),
	('Venture', 'Frigate', 'Trash'),
	('Vexor', 'Cruiser', 'DPS'),
	('Vexor Navy Issue', 'Cruiser', 'DPS'),
	('Viator', 'Blockade Run.', 'Cloaky Hauler'),
	('Vigil', 'Frigate', 'Tackle'),
	('Vigilant', 'Cruiser', 'DPS'),
	('Vindicator', 'Battleship', 'DPS'),
	('Vulture', 'Cmd. Ship', 'Booster'),
	('Widow', 'Black Ops', 'Black Ops'),
	('Wolf', 'Assault Frig.', 'Tackle'),
	('Worm', 'Frigate', 'Tackle'),
	('Wreathe', 'Industrial', 'Hauler'),
	('Wyvern', 'Supercarrier', 'Supercap'),
	('Zealot', 'H.A. Cruiser', 'DPS'),
	('Zephyr', 'Shuttle', 'Trash');